module.exports = {
	'DEFINITION_EN_US': {
		'yell_practice': 'A Texas A and M event that is similar to a pep rally. The most notable yell practices, Midnight Yell, occurs the night before home football games.',
		'yells': 'Synchronized yells done at Aggie sporting events.',
		'whoop': 'An exclamation of approval and excitement, especially used at the end of a yell.',
		'wildcat': 'A noise and a hand motion made after an Aggie yell. Each class uses a different wildcat based on seniority.',
		'war_hymn': 'Texas A and M\'s fight song',
		'ut': 'University of Texas',
		'tsip': 'A student of Texas A and M\'s archrival, The University of Texas at Austin.',
		'TAMC': 'Refers to the university\'s former name the \'Agricultural and Mechanical College of Texas\'. While the institution has been renamed Texas A&M University with the initials TAMU, the initials AMC are still used in several Aggie traditions including Aggie yells and the Spirit of Aggieland.',
		'silver_taps': 'A ceremony, held monthly, to honor all enrolled students who died in the previous month.',
		'ring_dunk': 'A non school sanctioned tradition performed after a student receives an Aggie Ring; usually involves chugging a pitcher of beer, or a non-alcoholic substitute, with their Aggie Ring in the bottom then catching the ring in their teeth.',
		'the_quad': 'Location of the dormitories of the Corps of Cadets.',
		'northgate': 'The entertainment district–mainly targeting A and M students–located north of the Texas A and M campus.',
		'new_army': 'Used to represent Texas A&M\'s current state and student body.',
		'muster': 'Tradition on 21 April, San Jacinto Day where Aggies from all over the world meet with each other and honor those Aggies who have died that year.',
		'maroon': 'The official color of Texas A and M along with white.',
		'hump': 'During a yell, the crowd leans forward and places their hands on their knees to maximize the amount of air displaced during the scream. The stance forces the diaphragm to assist the lungs.',
		'hullabaloo': 'Beginning phrase of the Aggie War Hymn. The lyrics are an onomatopoeic representation of the sound a cannon being loaded, or also the sound of a train rolling through town since there is a train track that splits the campus.',
		'howdy': 'Texas A and M University\'s official greeting. Students are encouraged to greet everyone they pass on campus with a smile and a howdy.',
		'fish_camp': 'An optional student-led four-day retreat for incoming freshmen held before the student\'s fall semester that introduces them to the traditions of Texas A and M University. Transfer students can attend a separate retreat called \'T-Camp\', and first time Texas A and M students coming in spring semester can attend \'Howdy Camp\'',
		'fish': 'A freshman student. In the Corps, the term is used in place of freshmen cadets\' first names and is always written in lowercase, e.g. \'fish Jones.\'',
		'band': 'Official band of Texas A and M since 1894. Members are cadets in the Corps and comprise an entire major unit of the Corps. The band is most noted for its straight line military marching and intricate close quarters drills.',
		'elephant_walk': 'A tradition where the senior class walks around campus to remember the times they had at Texas A&M.',
		'honor_code': 'Aggies do not lie, cheat, or steal, nor do they tolerate those who do.',
		'batt': 'The Battalion (often referred to simply as The Batt) is the student newspaper of Texas A and M University. Started in 1893 as a monthly publication, it continues to this day, now as a daily paper.',
		'aggieland': 'Name for Texas A and M and the surrounding metropolitan area, Bryan–College Station, Texas. The phrase, \'Welcome to Aggieland\', is on the watertower in the middle of campus and on one of the decks of Kyle Field.',
		'two_percenters': 'Aggies who choose not to participate in Texas A and M traditions.',
		'aggie': 'A student, alumnus, or supporter of Texas A&M University. Several other land grant schools use "Aggie", such as New Mexico State and UC Davis. Adding the name of the state at the beginning of the term (i.e. "Texas Aggie") is often used to distinguish between the different schools.',
		'helpdesk': '',
		'12_man': 'The 12th man or 12th player is a term for fans of teams in eleven-a-side sports games, particularly association football (soccer) or American football. As most football leagues allow a maximum of eleven players per team on the playing field at a time, referring to a team\'s fans as the 12th man implies that they have a potentially helpful role in the game.',
		'gig': 'Both a saying and the thumbs up hand gesture of all Texas A and M University current and former students as sign of affiliation.',
		'johnny_manziel': 'Johnathan Paul Manziel (born December 6, 1992) is an American football quarterback who is currently a free agent. He played for the Texas A and M Aggies as a redshirt freshman in Kevin Sumlin\'s Air Raid offense during A and M\'s first season in the SEC in 2012.',
		'tamu': 'Texas A and M University (Texas A and M, TAMU, or A and M) is a coeducational public research university in College Station, Texas, United States. It is a state university and since 1948 is a member of the Texas A and M University System. The Texas A and M system endowment is one of the 10 biggest in the nation. Texas A and M\'s student body is the largest in Texas and the second largest in the United States.',
		'corps': 'Texas A and M was established in 1876 as a military institution and the Corps of Cadets played an important part in our history and development. Membership in the Corps of Cadets is now voluntary.',
		'reville': 'Reveille, a full-blooded collie, is Texas A and M\'s mascot and the highest-ranking member of Texas A and M\'s Corp of Cadets. More information can be found at reveille.tamu.edu.',
		'howdy': 'Howdy! This is the official greeting of Texas A and M and has helped the university earn a reputation as the friendliest campus in the world.',
		'badbull': 'This term goes back to Texas A and M\'s beginnings as an agricultural school, since bad bull affects the herd and breaks tradition.',
		'goodbull': 'This signifies approval or describes anything embracing the traditions of Texas A and M University.',
	},
};